# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f840451b47fcfecc8657f84f7a8e90545a45ff6fa9cb023b7fbd0deee47152e05ce0d82862cf0d701ef67e3caefaf927a772a325adb278881577a2ddf283b6b5

test:
  secret_key_base: 708e8a0fbcbe1c2f359de724cf517d304f6b637940162319507d69557e97fc3655ca3f513889b5798abedcf0469ae4ac29c8d6277d23a58d111c5f9b5c5d77b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
